from typing import Union, ClassVar, TypeVar, Literal, List, Dict, Any, Type
import time
from pydantic import BaseModel, Field, ConfigDict

# 1. Type Variable for the OOI
OOI_T = TypeVar('OOI_T', bound='CodeChangeTask')

# 2. Base Class (The Core OOI Structure)
class CodeChangeTask(BaseModel):
    """The central Object of Importance for the feature."""
    model_config = ConfigDict(frozen=True)

    task_id: str
    created_at: float

    def copy_to(self, target_cls: Type[OOI_T], **kwargs) -> OOI_T:
        """
        Creates a new instance of target_cls using data from self,
        updated with kwargs. Used for State Transitions.
        """
        # Get current data
        current_data = self.model_dump()

        # Update with new data
        current_data.update(kwargs)

        # Actually, best way is to construct using fields present in target.
        target_fields = target_cls.model_fields.keys()

        # We must NOT copy the 'status' field from self, as the target class has its own literal value.
        # If we copy 'TaskRequested' status to 'ContextRetrieved' class, it fails validation.
        if 'status' in current_data:
            del current_data['status']

        init_data = {k: v for k, v in current_data.items() if k in target_fields}

        return target_cls(**init_data)

    def copy_with(self, **kwargs) -> 'CodeChangeTask':
        """
        Creates a new instance of the SAME class with updated fields.
        Used for intra-state updates (e.g., progress, refining query).
        Enforces validation by re-instantiating.
        """
        # Get current data
        current_data = self.model_dump()

        # Update with new data
        current_data.update(kwargs)

        # Re-instantiate to enforce validation
        # self.__class__ refers to the concrete subclass (e.g., TaskRequested)
        return self.__class__(**current_data)


# 3. State Subclasses (The Valid Shapes/Discriminated Union Members)
class TaskRequested(CodeChangeTask):
    """Initial state when a task is requested by the user."""
    query: str
    status: Literal['TaskRequested'] = 'TaskRequested'

class ContextRetrieved(CodeChangeTask):
    """State after context (search results) has been retrieved."""
    query: str
    search_results: List[Dict[str, Any]]
    status: Literal['ContextRetrieved'] = 'ContextRetrieved'

class PatchGenerated(CodeChangeTask):
    """State after a JSON patch has been generated by the LLM."""
    query: str
    search_results: List[Dict[str, Any]]
    patch: Union[Dict[str, Any], List[Dict[str, Any]]] # JSON Patch can be a list
    status: Literal['PatchGenerated'] = 'PatchGenerated'

class ChangeCommitted(CodeChangeTask):
    """State after the patch has been applied and committed."""
    query: str
    search_results: List[Dict[str, Any]]
    patch: Union[Dict[str, Any], List[Dict[str, Any]]]
    commit_hash: str
    status: Literal['ChangeCommitted'] = 'ChangeCommitted'

# 4. The OOI Union (The Complete Type Definition)
CodeChangeTaskState = Union[TaskRequested, ContextRetrieved, PatchGenerated, ChangeCommitted]
