name: Publish Docker Images

on:
  push:
    branches: ["main"]
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_GIT_AI: ${{ github.repository_owner }}/git-ai
  IMAGE_NAME_INDEXER: ${{ github.repository_owner }}/git-ai-indexer

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        include:
          - context: git-ai
            image: git-ai
            dockerfile: git-ai/Dockerfile
          - context: indexer-service
            image: indexer-service
            dockerfile: indexer-service/Dockerfile

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/${{ matrix.image }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
